name: Nightly workflow

on:
  schedule:
    - cron: "0 17 22 * *"

jobs:
  first-cron-job:
    name: "Cronが実行できるかどうかチェック"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.15.3]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - name: Display versions
        run: |
          node -v
          npm -v
          yarn --version
