name: Cron test

on:
  schedule:
    - cron: "55 9 * * *" # UTCであることに注意。日本標準時の現在時刻(JST/UTC+0900)なので、日本時間から「-9時間」

jobs:
  first-cron-job:
    name: "Cronが実行できるかどうかチェック"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.15.3]
    steps:
      - uses: actions/checkout@v2 # git checkoutを使用
        with:
          ref: development # 特定のbranchにチェックアウトできる
      - name: Display versions
        run: |
          node -v
          npm -v
          yarn --version
      - name: Check Branch
        run: |
          node cron.js
