on:
  push:
    # branches:
    branches-ignore:
      - master

name: github-actions-101-mongodb

jobs:
  vm-mongodb-github-actions-job:
    name: "VMでNode.js/MongoDBを使用できるかどうかチェック"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.15.3]
    services:
      mongodb:
        image: circleci/mongo:3.6.9
        ports:
          - 27017:27017
        env:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
        options: --name mongodb
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: mongoDB client installation
        run: sudo apt-get install mongodb-clients
      - name: Display version of Node.js, npm, Yarn
        run: |
          node -v
          npm -v
          yarn --version
          mongo --version
  # docker-mongodb-github-actions-job:
  #   name: "DockerでNode.js/MongoDBを使用できるかどうかチェック"
  #   runs-on: ubuntu-latest
  #   container:
  #     image: circleci/node:10.15.3
  #     env:
  #       TZ: "/usr/share/zoneinfo/Asia/Tokyo"
  #   services:
  #     mongodb:
  #       image: circleci/mongo:3.6.9
  #       ports:
  #         - 27017:27017
  #       env:
  #         TZ: "/usr/share/zoneinfo/Asia/Tokyo"
  #       options: --name mongodb
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: node -v
  #     - run: npm -v
  #     - run: yarn --version
