on:
  pull_request:
    branches:
      - development

name: github-actions-101-pull-request

jobs:
  error:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.18.1]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Error
        run: mongo --version # 絶対にエラーになる
