name: deploy-staging

on:
  push:
    branches:
      - "release-v3*" # staging 用
      - "hotfix-v3*" # staging 用


name: staging-branch-test

jobs:
  staging-branch-test:
    runs-on: ubuntu-latest # ジョブが実行される仮想環境
    steps: # ジョブ内で実行されるステップ
      - run: echo "Hello, World!" # ステップで実行するコマンド
